SEO-171351 ASP.NET Core Bing reports
syncfusion-content/asp.net-core-docs pull request #333
Opened 2023-04-26 10:01 UTC by Yvone-Atieno

Hi @Aishwarya-Ganesan ,

Have changed description, title, h1, redirect links and image alt.

Regards,
Yvone.

2023-04-26 10:03 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO-171351-ASP.NET-Core-Bing-reports](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/157/console)**

2023-04-26 10:03 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171351-ASP.NET-Core-Bing-reports](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/157/)<br/>**

2023-05-03 07:01 UTC, gowthamanthavasiyappan requested changes
Commented

2023-05-03 07:01 UTC, gowthamanthavasiyappan commented on aspnet-core/TimePicker/Overview.md
> +# Overview of ASP.NET Core TimePicker Control
Remove control word

2023-05-03 11:36 UTC, Yvone-Atieno commented on aspnet-core/TimePicker/Overview.md
> +# Overview of ASP.NET Core TimePicker Control
removed

2023-05-03 11:38 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO-171351-ASP.NET-Core-Bing-reports](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/158/)<br/>**

2023-05-04 04:16 UTC, gowthamanthavasiyappan approved these changes
Approved

2023-05-04 09:38 UTC, Girija-Rajendran approved these changes

2023-05-04 13:12 UTC, merged