SEO-171884 ASP.NET Core - Permanent Redirect
syncfusion-content/asp.net-core-docs pull request #337
Opened 2023-05-09 08:50 UTC by Thahira-Banu

Hi @Aishwarya-Ganesan 

I have made changes in the permanent redirect links by changing the title,  h1 tag,URL

2023-05-09 08:51 UTC, SyncfusionBuild commented
The running **[CI Job](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/160/console)** is terminated due to changes committed on the source branch for this Merge Request and CI triggered for latest commit.

2023-05-09 08:52 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO---171884---ASP.NET-Core-Permanent-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/161/console)**

2023-05-09 08:54 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO---171884---ASP.NET-Core-Permanent-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/161/)<br/>**

2023-05-10 04:13 UTC, gowthamanthavasiyappan requested changes
Commented

2023-05-10 04:13 UTC, gowthamanthavasiyappan commented on aspnet-core/Overview.md
> +title: Overview for ASP.NET Core Application | Syncfusion
Recheck this title.

2023-05-17 12:57 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO---171884---ASP.NET-Core-Permanent-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/165/)<br/>**

2023-05-18 06:04 UTC, gowthamanthavasiyappan requested changes
Commented

2023-05-18 10:28 UTC, Thahira-Banu commented on aspnet-core/Overview.md
> +* Another valuable resource is the [API reference](https://help.syncfusion.com/cr/aspnet-core/Syncfusion.CompoundFile.DocIO.html) which provides detailed information on the object hierarchy as well a
Checked, this is fine to change

2023-05-18 10:31 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO---171884---ASP.NET-Core-Permanent-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/166/)<br/>**

2023-05-18 11:04 UTC, gowthamanthavasiyappan requested changes
Commented

2023-05-18 11:04 UTC, gowthamanthavasiyappan commented on aspnet-core/Overview.md
> +title:  Welcome to Syncfusion Essential ASP.NET Core
Remove unwanted space here.

2023-05-18 11:32 UTC, Thahira-Banu commented on aspnet-core/Overview.md
> +title: About ASP.NET Core Application | Syncfusion
Resolved

2023-05-18 11:33 UTC, Thahira-Banu commented on aspnet-core/Overview.md
> +title:  Welcome to Syncfusion Essential ASP.NET Core
Resolved

2023-05-18 11:36 UTC, SyncfusionBuild commented
**Build Status: INQUEUE :clock3:<br/>Build Location: [SEO---171884---ASP.NET-Core-Permanent-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/167/console)**

2023-05-18 11:37 UTC, SyncfusionBuild commented
**Build Status: INPROGRESS :arrows_clockwise:<br/>Build Location: [SEO---171884---ASP.NET-Core-Permanent-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/167/console)**

2023-05-18 11:39 UTC, SyncfusionBuild commented
**CI Status: SUCCESS :white_check_mark:<br/>Source Compilation: SUCCESS :white_check_mark:<br/>Build Location: [SEO---171884---ASP.NET-Core-Permanent-redirect-](https://jenkins.syncfusion.com/job/Content/job/asp.net-core-docs/167/)<br/>**

2023-05-18 11:41 UTC, gowthamanthavasiyappan approved these changes
Approved

2023-05-18 12:00 UTC, Girija-Rajendran approved these changes

2023-05-30 12:01 UTC, Girija-Rajendran approved these changes

2023-05-30 12:38 UTC, Girija-Rajendran approved these changes

2023-05-30 12:42 UTC, merged